-- Neovim configuration
require("plugins")
require("globals")
require("settings")
require("core")

-- Editor features
require("autopairs")
require("colorschemes")
require("completion")
require("debugging")
require("explorer")
require("folding")
require("formatting")
require("git")
require("lsp")
require("mappings")
require("quicklist")
require("spelling")
require("start")
require("statusline")
require("transparency")
require("tree-sitter")
require("tests")
