-- Neovim configuration
require('plugins')
require('globals')
require('settings')

-- Editor features
require('autopairs')
require('colorschemes')
require('completion')
require('explorer')
require('folding')
require('formatting')
require('git')
require('lsp')
require('mappings')
require('quicklist')
require('spelling')
require('statusline')
require('tree-sitter')
require('welcome_screen')
